#!/usr/bin/env node
// Prints an `op run --env-file` template for one service on the VPS: the [variables] of
// .1password/project.toml (op:// references and non-secret literals, never values), with
// production overrides. Secrets resolve only inside the process that `op run` starts.
//
//   node deploy/render-env.mjs app        > /etc/docent/app.env.tpl
//   node deploy/render-env.mjs voice      > /etc/docent/voice.env.tpl
//   node deploy/render-env.mjs litestream > /etc/docent/litestream.env.tpl
//
// SITE_DOMAIN (default: brand.domain from lib/brand.ts) sets the public host.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = process.argv[2];

function manifestVariables() {
  const text = fs.readFileSync(path.join(root, ".1password", "project.toml"), "utf8");
  const vars = new Map();
  let inVariables = false;
  for (const line of text.split("\n")) {
    const header = line.match(/^\s*\[(.+)\]\s*$/);
    if (header) {
      inVariables = header[1] === "variables";
      continue;
    }
    const entry = inVariables && line.match(/^\s*([A-Z][A-Z0-9_]*)\s*=\s*"([^"]*)"/);
    if (entry) vars.set(entry[1], entry[2]);
  }
  return vars;
}

function brandDomain() {
  const text = fs.readFileSync(path.join(root, "lib", "brand.ts"), "utf8");
  return text.match(/domain:\s*"([^"]+)"/)?.[1];
}

const domain = process.env.SITE_DOMAIN || brandDomain();
const DATA = "/var/lib/docent/data";
const vars = manifestVariables();
const pick = (...names) => names.map((n) => [n, vars.get(n)]).filter(([, v]) => v !== undefined);

const targets = {
  app: () => [
    ...vars,
    ["APP_ENV", "production"],
    ["NODE_ENV", "production"],
    ["APP_BASE_URL", `https://${domain}`],
    ["HOSTNAME", "127.0.0.1"],
    ["PORT", "3000"],
    ["DATABASE_PATH", `${DATA}/palmetto.sqlite`],
    // ElevenLabs stays the default engine. VOICE_STREAM_URL alone changes nothing; set
    // PROSPECT_VOICE_ENGINE=selfhosted in the Environment to route phone calls to voice/.
    ["VOICE_STREAM_URL", `wss://${domain}/voice/twilio`],
  ],
  voice: () => [
    ...pick("LLM_RELAY_SECRET", "TOOL_WEBHOOK_SECRET", "TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"),
    // Loopback: the relay and tool calls never leave the host.
    ["APP_BASE_URL", "http://127.0.0.1:3000"],
    // TODO: no canonical item yet; voice/README.md reads TOGETHER_API_KEY from voice/.env today.
    ["TOGETHER_API_KEY", vars.get("TOGETHER_API_KEY") ?? "op://Dev/Together AI/credential"],
  ],
  litestream: () => [
    ...pick("LITESTREAM_ACCESS_KEY_ID", "LITESTREAM_SECRET_ACCESS_KEY", "LITESTREAM_BUCKET", "LITESTREAM_ENDPOINT", "LITESTREAM_REGION", "LITESTREAM_PATH"),
    ["DOCENT_DATA_DIR", DATA],
  ],
};

if (!targets[target]) {
  console.error(`usage: render-env.mjs ${Object.keys(targets).join("|")}`);
  process.exit(2);
}
const merged = new Map(targets[target]());
console.log(`# Generated by deploy/render-env.mjs ${target}. op:// references only; no secret values.`);
for (const [name, value] of merged) console.log(`${name}=${value}`);
